/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2018 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include "Messages.h"

uint8_t pcint0_history = 0;
uint8_t pcint1_history = 0;
uint8_t pcint2_history = 0;
uint8_t pcint3_history = 0;

volatile bool touchEventDetected = false;
uint8_t EVENTS = 0;
uint16_t SWITCH_STATES = 0;

ISR(PCINT0_vect)
{

	/* Insert your pin change 0 interrupt handling code here */
   // Interrupts 0 to 7
   uint8_t changedbits;

   changedbits = PINB ^ pcint0_history;
   pcint0_history = PINB;
   
   if(changedbits & _BV(INT_PLAY_PAUSE))
   {
      bit_is_set(PINB, INT_PLAY_PAUSE) ? (SWITCH_STATES &= ~(_BV(SWITCH_PLAY_PAUSE))) : (SWITCH_STATES |= _BV(SWITCH_PLAY_PAUSE));
   }
   else if(changedbits & _BV(INT_REWIND))
   {
      bit_is_set(PINB, INT_REWIND) ? (SWITCH_STATES &= ~(_BV(SWITCH_REWIND))) : (SWITCH_STATES |= _BV(SWITCH_REWIND));
   }
   else if(changedbits & _BV(INT_C))
   {
      bit_is_set(PINB, INT_C) ? (SWITCH_STATES &= ~(_BV(SWITCH_C))) : (SWITCH_STATES |= _BV(SWITCH_C));
   }
   else if(changedbits & _BV(INT_B))
   {
      bit_is_set(PINB, INT_B) ? (SWITCH_STATES &= ~(_BV(SWITCH_B))) : (SWITCH_STATES |= _BV(SWITCH_B));
   }
   else if(changedbits & _BV(INT_A))
   {
      bit_is_set(PINB, INT_A) ? (SWITCH_STATES &= ~(_BV(SWITCH_A))) : (SWITCH_STATES |= _BV(SWITCH_A));
   }
   else if(changedbits & _BV(INT_VOL_DN))
   {
      bit_is_set(PINB, INT_VOL_DN) ? (SWITCH_STATES &= ~(_BV(SWITCH_VOL_DN))) : (SWITCH_STATES |= _BV(SWITCH_VOL_DN));
   }
}

ISR(PCINT1_vect)
{

	/* Insert your pin change 1 interrupt handling code here */
	// Interrupts 8 to 14
   uint8_t changedbits;

   changedbits = PINC ^ pcint1_history;
   pcint1_history = PINC;
   
   if(changedbits & _BV(INT_ENTER))
   {
      bit_is_set(PINC, INT_ENTER) ? (SWITCH_STATES &= ~(_BV(SWITCH_ENTER))) : (SWITCH_STATES |= _BV(SWITCH_ENTER));
   }
   else if(changedbits & _BV(INT_ZONE))
   {
      bit_is_set(PINC, INT_ZONE) ? (SWITCH_STATES &= ~(_BV(SWITCH_ZONE))) : (SWITCH_STATES |= _BV(SWITCH_ZONE));
   }
   else if(changedbits & _BV(INT_BACK))
   {
      bit_is_set(PINC, INT_BACK) ? (SWITCH_STATES &= ~(_BV(SWITCH_BACK))) : (SWITCH_STATES |= _BV(SWITCH_BACK));
   }
}

ISR(PCINT2_vect)
{

	/* Insert your pin change 2 interrupt handling code here */
	// Interrupts 16 to 23
   uint8_t changedbits;

   changedbits = PIND ^ pcint2_history;
   pcint2_history = PIND;
   
   if(changedbits & _BV(T84_DATA_READY_INT))
   {
	   if(bit_is_clear(PIND, T84_DATA_READY_INT))
	   {
	      touchEventDetected = true;
	   }
   }
   else if(changedbits & _BV(INT_MUSIC))
   {
      bit_is_set(PIND, INT_MUSIC) ? (SWITCH_STATES &= ~(_BV(SWITCH_MUSIC))) : (SWITCH_STATES |= _BV(SWITCH_MUSIC));
   }
   else if(changedbits & _BV(INT_FORWARD))
   {
      bit_is_set(PIND, INT_FORWARD) ? (SWITCH_STATES &= ~(_BV(SWITCH_FORWARD))) : (SWITCH_STATES |= _BV(SWITCH_FORWARD));
   }
}

ISR(PCINT3_vect)
{

	/* Insert your pin change 3 interrupt handling code here */
	// Interrupts 24 to 27
   uint8_t changedbits;

   changedbits = PINE ^ pcint3_history;
   pcint3_history = PINE;
   
   if(changedbits & _BV(INT_VOL_UP))
   {
      bit_is_set(PINE, INT_VOL_UP) ? (SWITCH_STATES &= ~(_BV(SWITCH_VOL_UP))) : (SWITCH_STATES |= _BV(SWITCH_VOL_UP));
   }
   else if(changedbits & _BV(INT_MUTE))
   {
      bit_is_set(PINE, INT_MUTE) ? (SWITCH_STATES &= ~(_BV(SWITCH_MUTE))) : (SWITCH_STATES |= _BV(SWITCH_MUTE));
   }
}
